<?php
/**
 * Snippet Title: Shortcodes Prev-suiv
 * Snippet ID: 676
 * Snippet Description: Créé des shortcodes pour naviguer entre les articles de blog. Pour délimiter le texte affiché, modifier la valeur 'lengh" pour les 2 shortcodes
 * Snippet type: include
 * Usage: This snippet is included in your website. You can used add_action or add_filter in this type of snippet. The code is included before WordPress hooks.
 * Generated at: 2024-12-09 16:22:34
 *
 * @author This code snippet is generated by WPMasterToolkit
 * @link https://dev.le-grizzly.fr/rencontre-gratuit/wp-admin/post.php?post=676&action=edit
 * @since 1.14.0
 *
**/
function shortcode_previous_post_link($atts) {
    $atts = shortcode_atts(
        array(
            'length' => 45, // Longueur maximale du titre
        ),
        $atts,
        'previous_post_link'
    );

    $previous_post = get_previous_post();
    if (!empty($previous_post)) {
        $title = get_the_title($previous_post->ID);
        $trimmed_title = mb_strimwidth($title, 0, $atts['length'], '...');
        return '<a href="' . get_permalink($previous_post->ID) . '">' . esc_html($trimmed_title) . '</a>';
    }
    return '';
}
add_shortcode('previous_post_link', 'shortcode_previous_post_link');

function shortcode_next_post_link($atts) {
    $atts = shortcode_atts(
        array(
            'length' => 45, // Longueur maximale du titre
        ),
        $atts,
        'next_post_link'
    );

    $next_post = get_next_post();
    if (!empty($next_post)) {
        $title = get_the_title($next_post->ID);
        $trimmed_title = mb_strimwidth($title, 0, $atts['length'], '...');
        return '<a href="' . get_permalink($next_post->ID) . '">' . esc_html($trimmed_title) . '</a>';
    }
    return '';
}
add_shortcode('next_post_link', 'shortcode_next_post_link');