<?php
/**
 * Snippet Title: Total site
 * Snippet ID: 1715
 * Snippet Description: Compte le nombre de site total publié.
Utilisé pour la page d'accueil
 * Snippet type: include
 * Usage: This snippet is included in your website. You can used add_action or add_filter in this type of snippet. The code is included before WordPress hooks.
 * Generated at: 2025-03-26 17:12:14
 *
 * @author This code snippet is generated by WPMasterToolkit
 * @link https://sitederencontregratuit.com/wp-admin/post.php?post=1715&action=edit
 * @since 2.4.1
 *
**/
function count_published_sites_posts() {
    return wp_count_posts('sites')->publish;
}
add_shortcode('count_sites', 'count_published_sites_posts');